### PR TITLE
Python3 version for downloads.py

### PR DESCRIPTION
**Pull request by nakumgaurav**
The original code used urllib which generated SSL certificate error and which according to https://docs.python.org/3.4/library/urllib.request.html#legacy-interface may be deprecated in the future. I am now using Python3's requests library for downloading the datasets. Also, I have updated the outdated website links for some datasets, as indicated in my earlier pull requests.

### CODE REVIEW

**Comment by leonweber** [comment]
Hey @nakumgaurav thanks for reporting this! I will verify that it does not break anything, and then merge.

**Comment by leonweber** [comment]
I am getting an error for the CLL corpus. @nakumgaurav does that work for you?

```bash
cll is missing. Downloading...
Traceback (most recent call last):
  File "download_files.py", line 158, in <module>
    with tarfile.open('cll.tar.gz') as f:
  File "/home/leon/anaconda3/lib/python3.6/tarfile.py", line 1576, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

**Comment by nakumgaurav** [comment]
Hey @leonweber thanks a lot for reviewing the changes. As you can see for yourself, the link for the CLL corpus is broken: http://bionlp-www.utu.fi/cell-lines/CLL_corpus.tar.gz. It gives a 404 error. Note that the site for Gellus corpus is the same, but its link works just fine. 

Additionally, I have made some other changes. Let me know if it works now for all corpora (excluding CLL)

**Comment by nakumgaurav** [comment]
I contacted the CLL authors (attached) and it seems it would take them this week to update the links. Let me know if there are any other changes worth making to the file.

image

**Comment by leonweber** [comment]
Looks good. I'm merging this. @nakumgaurav thank you very much for your contribution!

**Review by leonweber — COMMENTED** [review]
Looks good!

**Pull request merged**
